# Numpy
The fundamental package for scientific computing with Python

**1. Powerful N-dimensional arrays**\
Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

**2. Numerical computing tools**\
NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.


**3. Interoperable**\
NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

**4. Performant**\
The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

In [1]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print("For loop: " + str(1000*(toc-tic)) + "ms")

For loop: 641.0245895385742ms


In [2]:

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorised version: " + str(1000*(toc-tic)) + "ms")

Vectorised version: 16.32833480834961ms


**5. Easy to use**\
NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

In [3]:
import numpy as np

In [4]:
a = np.array(([1,2],[3,4]))

In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b = np.array(([5,6],[7,8]))
b

array([[5, 6],
       [7, 8]])

In [7]:
a*b

array([[ 5, 12],
       [21, 32]])

In [8]:
a+b

array([[ 6,  8],
       [10, 12]])

In [9]:
a-b

array([[-4, -4],
       [-4, -4]])

what about matrix multiplication **not element-wise multiplication**? 
## 내적

In [13]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

determinant? 

In [14]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

inverse? 

In [15]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

many zeros 

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

what about many ones? 

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## List vs ArrayList

In [21]:
a = [1, 2]
a

[1, 2]

In [22]:
type(a)

list

In [23]:
b = np.array([1,2])

In [24]:
type(b)

numpy.ndarray

In [25]:
np.asarray(a)

array([1, 2])

In [26]:
np.array(a)

array([1, 2])

what about back to list ? 

In [27]:
np.array([[1,2,3],[4,5,6]]).tolist()

[[1, 2, 3], [4, 5, 6]]

## basic indexing

In [28]:
x = np.arange(5,10)

In [29]:
x

array([5, 6, 7, 8, 9])

arange: Return evenly spaced values within a given interval.

In [30]:
np.arange(5,10,2)

array([5, 7, 9])

In [31]:
x[0]

np.int64(5)

In [32]:
x[3]

np.int64(8)

last index?  Let's count....

In [33]:
x[4]

np.int64(9)

don't want to count 

In [34]:
x[-1]

np.int64(9)

any number? 

In [35]:
x[9]

IndexError: index 9 is out of bounds for axis 0 with size 5

In [36]:
x[-1.0]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [37]:
x[-2]

np.int64(8)

## basic slicing and striding

In [38]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [39]:
x[1:7:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [40]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [41]:
x[:4]

array([0, 1, 2, 3])

In [42]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x[-1]

np.int64(9)

In [44]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
x[-3:]

array([7, 8, 9])

## advanced indexing

Integer array indexing

In [47]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
x[np.array([4,2])]

array([9, 7])

In [49]:
x[[4,2]]

array([9, 7])

## repeat

In [50]:
a = np.array(([1,2],[3,4]))
a.shape

(2, 2)

## axis0: 행, axis1: 열

In [51]:
np.repeat(a, 3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [52]:
np.repeat(a, 2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [55]:
np.repeat(a, 2,axis=-1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## flatten: 1차원

In [56]:
a.flatten()

array([1, 2, 3, 4])

In [62]:
a.flatten().shape

(4,)

In [57]:
b = np.array(([5,6],[7,8]))

In [58]:
b

array([[5, 6],
       [7, 8]])

## concatenate, 갖다 붙임, 기본적으로 행 방향으로 (axis=0)

In [63]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [66]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## reshape

In [67]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

## -1: 자동으로 계산해라, Depth, Height, Width | 높이, 행, 열

In [68]:
np.arange(12).reshape((2,-1,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## 다 1차원으로 펴라

In [72]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [66]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [67]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [74]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

## squeeze 1차원변환

remove axes of length one from input

In [76]:
t = np.arange(6)

In [77]:
t.shape

(6,)

In [78]:
t = np.reshape(t,(6,1))

In [79]:
t.shape

(6, 1)

In [80]:
c = np.squeeze(t)

In [81]:
c.shape

(6,)

## stack

Join a sequence of arrays along a new axis.

In [81]:
array = np.random.randn(3, 4) 
array

array([[ 2.12852   ,  0.85285248, -1.87484068, -1.13865811],
       [ 0.19124225, -1.29986493, -1.13642684,  0.0439745 ],
       [ 0.46758571,  1.05551904,  0.33552681,  1.35843209]])

In [84]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [85]:
arrays = [array for _ in range(10)]
arrays

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [88]:
array1 = np.stack(arrays, axis=0)
array1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [89]:
np.stack(arrays, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [90]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [92]:
np.stack(arrays, axis=1)

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12]]])

In [94]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [95]:
np.stack(arrays, axis=2)

array([[[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]],

       [[ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]],

       [[ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]]])

## vstack

stack arrays in sequence vertically (row wise)

In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [91]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [93]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## hstack

Stack arrays in sequence horizontally (column wise)

In [94]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [95]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [96]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [97]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## concat

In [98]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)

[[1 2]
 [3 4]]


In [99]:
print(b)

[[5 6]]


In [100]:
b.shape

(1, 2)

In [101]:
c = np.array([5,6])

In [109]:
print(c)
#1차원

[5 6]


In [103]:
c.shape

(2,)

In [104]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [106]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [107]:
np.concatenate((a, c), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## concatenate는 차원 일치가 되어야 하지만 vstack은 그냥 쌓아진다

In [110]:
np.vstack((a,c))

array([[1, 2],
       [3, 4],
       [5, 6]])

why work? 

This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N).

## split

Split an array into multiple sub-arrays as views into ary.

In [96]:
x = np.arange(9.0)

In [97]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [98]:
np.split(x, 4)

ValueError: array split does not result in an equal division

처음 ~ 인덱스 3 전까지: x[:3] → [0.0, 1.0, 2.0]  
인덱스 3 ~ 인덱스 5 전까지: x[3:5] → [3.0, 4.0]  
인덱스 5 ~ 인덱스 6 전까지: x[5:6] → [5.0]  
인덱스 6 ~ 인덱스 10 전까지: x[6:10] → [6.0, 7.0]  
인덱스 10 ~ 끝까지: x[10:] → [] (빈 배열)

In [114]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

## vsplit

In [101]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [102]:
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]),
 array([[[4., 5.],
         [6., 7.]]])]

In [105]:
a = np.vsplit(x,2)
a[0]

array([[[0., 1.],
        [2., 3.]]])

In [106]:
a[0].shape

(1, 2, 2)

array is always split along the first axis regardless of the array dimension.

## hsplit

In [107]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [108]:
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]),
 array([[[2., 3.]],
 
        [[6., 7.]]])]

Split an array into multiple sub-arrays horizontally (column-wise).
hsplit is equivalent to split with axis=1

## flip 뒤집기

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [109]:
A = np.arange(8).reshape((2,2,2))

In [110]:
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
np.flip(A,0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [113]:
np.flip(A,1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [114]:
np.flip(A,2)

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [116]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [117]:
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

In [118]:
np.trim_zeros(a,'f') # front

array([1, 2, 3, 0, 2, 1, 0])

In [119]:
np.trim_zeros(a,'b')

array([0, 0, 0, 1, 2, 3, 0, 2, 1])

In [120]:
np.ma.masked_equal(a,0)

masked_array(data=[--, --, --, 1, 2, 3, --, 2, 1, --],
             mask=[ True,  True,  True, False, False, False,  True, False,
                   False,  True],
       fill_value=0)