# Numpy

In [4]:
import numpy as np

In [5]:
a = np.array(([1,2],[3,4]))

In [6]:
a

array([[1, 2],
       [3, 4]])

## basic indexing

In [7]:
x = np.arange(5,10)

In [8]:
x

array([5, 6, 7, 8, 9])

In [9]:
x[-2]

np.int64(8)

## basic slicing and striding

In [10]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [11]:
x[1:7:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [12]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [13]:
x[:4]

array([0, 1, 2, 3])

In [14]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[-1]

np.int64(9)

In [16]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
x[-3:]

array([7, 8, 9])

## advanced indexing

Integer array indexing

In [18]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
x[np.array([4,2])]

array([9, 7])

## repeat

In [40]:
a = np.array(([1,2],[3,4]))
a.shape

(2, 2)

In [41]:
np.repeat(a, 3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [42]:
np.repeat(a, 2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [44]:
np.repeat(a, 2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

## flatten

In [45]:
a.flatten()

array([1, 2, 3, 4])

In [46]:
b = np.array(([5,6],[7,8]))

In [47]:
b

array([[5, 6],
       [7, 8]])

## concatenate

In [48]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [51]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## reshape

In [43]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [52]:
np.arange(12).reshape((2,-1,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.reshape(a, (3,-1,))

array([[1, 2],
       [3, 4],
       [5, 6]])

## squeeze
## 저 (6,)은 1차원 (6,1)은 2차원이다. 다른거임

remove axes of length one from input

In [53]:
t = np.arange(6)

In [54]:
t.shape

(6,)

In [55]:
t = np.reshape(t,(6,1))

In [56]:
t.shape

(6, 1)

In [58]:
np.squeeze(t).shape

(6,)

## stack

Join a sequence of arrays along a new axis.

In [68]:
array = np.arange(12).reshape(3, 4) 
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
np.stack(array, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.stack(array, axis=1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [71]:
np.stack(array, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

## vstack

stack arrays in sequence vertically (row wise)

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [22]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [24]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## hstack

Stack arrays in sequence horizontally (column wise)

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [26]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [28]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## split

Split an array into multiple sub-arrays as views into ary.

In [31]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [32]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [33]:
np.split(x, 4)

ValueError: array split does not result in an equal division

In [34]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

## flip

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [35]:
A = np.arange(8).reshape((2,2,2))

In [36]:
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
np.flip(A,0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [38]:
np.flip(A,1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [39]:
np.flip(A,2)

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [ ]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [ ]:
np.trim_zeros(a)

In [ ]:
np.trim_zeros(a,'f')

In [ ]:
np.trim_zeros(a,'b')

In [ ]:
np.ma.masked_equal(a,0)